image:
  file: .gitpod.Dockerfile

ports:
  # Rails server
  - port: 3000
    onOpen: open-preview
  # PostgreSQL server
  - port: 5432
    onOpen: ignore

tasks:
  - name: Setup
    init: >
      cp .env.example .env &&
      bin/setup &&
      bundle exec rake db:seed &&
      gp sync-done setup
  - name: Rails
    command: >
      gp sync-await setup &&
      rails server -b 0.0.0.0
  - name: Webpack
    command: >
      gp sync-await setup &&
      webpack-dev-server

# Enable prebuilds of your project to enable faster workspace start times.
# https://www.gitpod.io/docs/prebuilds/#configure-the-github-app
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true

vscode:
  extensions:
    - rebornix.ruby
